config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  resources :to_dos
  devise_for :users
  root to:"homes#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/to_do.rb
class ToDo < ApplicationRecord
    belongs_to :user



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :to_dos, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        "/to_dos"
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
    before_action :set_todo, only: [:show, :edit, :update, :destroy]
    def index
        @todos = current_user.to_dos
    end
    def new
        @todo = current_user.to_dos.new
    end
    def create
        @todo=current_user.to_dos.new(todo_params)

        respond_to do |format|
            if @todo.save
              format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
              format.json { render :show, status: :created, location: @todo }
            else
              format.html { render :new }
              format.json { render json: @todo.errors, status: :unprocessable_entity }
            end
        end
    end
    def destroy
        @todo.destroy
        respond_to do |format|
          format.html { redirect_to to_dos_path, notice: 'Todo was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
    def todo_params
        params.require(:to_do).permit(:name, :due)
    end
    def set_todo
        @todo = current_user.to_dos.find(params[:id])
      end
    def show
        @todo = current_user.to_dos.find(params[:id])
    end
    def update
        respond_to do |format|
          if @todo.update(todo_params)
            format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
            format.json { render :show, status: :ok, location: @todo }
          else
            format.html { render :edit }
            format.json { render json: @todo.errors, status: :unprocessable_entity }
          end
        end
      end
      def edit
        @todo = current_user.to_dos.find(params[:id])
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/homes/index.html.erb
<h1>To Do List</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
  <%if user_signed_in?%>
    <%= link_to "Logout", destroy_user_session_path,method: :delete%>
    <% else %>
    <%= link_to "Login", user_session_path %>
    <%= link_to "signup","users/sign_up" %>
    <% end %>
  </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/to_dos/edit.html.erb
<h1>Edit Todo</h1>
<%= form_for @todo, url: {action: "update"} do |f|%>
    <%=f.text_field :name%>
    <%=f.date_field, type:'date', html: {:max=> '2018-02-02'} :due%>
    tag('input', :data => {:type => 'date', :max => '2018-02-02'})
    <%=f.submit "Save"%>
<% end %>

app/views/to_dos/index.html.erb
<h1>Todos list</h1>
<% if not @todos.nil? %>
    <%@todos.each do |todo|%>
        <tr>
            <td><%=todo.name%></td>
            <td><%=todo.due%></td>
            <td><%= link_to 'Show', todo %></td>
            <td><%= link_to 'Edit', edit_to_do_path(todo) %></td>
            <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
<% end %>
<%= link_to 'new todo',new_to_do_path %>

app/views/to_dos/new.html.erb
<h1>CREAT Todo</h1>
<%= form_for @todo, url: {action: "create"} do |f|%>
    <%=f.text_field :name%>
    <%=f.date_field :due%>

    <%=f.submit "Save"%>
<% end %>

app/views/to_dos/show.html.erb
<%=@todo.name%>

<%= link_to 'back' , to_dos_path%>